### PR TITLE
alternative suggestion for homepage text

### PR DESCRIPTION
**Pull request by martinklepsch**
My goal with these changes is mostly a change of tone towards community and openness.

I personally don't think there is much value in saying things like "we will not invite extremely hyped talks."

- [ ] I was wondering if we might want to change "Clojure" to "Clojure(Script)" in this bit: "Focus points will be interesting developments and ideas in the global Clojure community". ClojureScript is becoming a very established part in this Community and acknowledging that can't hurt.
- [ ] Maybe we have a picture that better showcases the social aspect of the conference?
- [ ] I changed the section about the involvement of the university a bit, I hope it still accurately reflects the situation, please let me know if it doesn't. :blush: 
- [ ] The "contact us" bit needs a proper email address, do we have one that forwards to everyone?

@edlich @nblumoe thoughts?

### CODE REVIEW

**Comment by edlich** [comment]
I really do like all comments.
I just hope no official of my university ready this. Because Beuth really conducts (!) this conference (not just supporting ;-)

**Comment by martinklepsch** [comment]
> I just hope no official of my university ready this. Because Beuth really conducts (!) this conference (not just supporting ;-)

I understand. I'd be happy about alternative suggestions. My thinking was to make it clearer that this is an event that's not organized by an unknown third party but rather by actual members of the community. IMO this guarantees some alignment to potential speakers/attendees that's not given if there is a "faceless institution" behind the conference (this is dramatically phrased but I guess you get the general idea).

**Comment by martinklepsch** [comment]
@edlich can you create a `hello@clojured.de` email that forwards to all of us?

@clojureD-conference/owners any more thoughts on these changes? Would be great to get this in soon.

**Comment by nblumoe** [comment]
I really like the changes, would merge but we still have the missing "contact us" link. Could be changed to http://www.clojured.de/contact/ to make it "mergable".

Regarding the additional proposals:

- I am fine with Clojure(Script)

- Regarding a nicer photo, maybe something from https://www.dropbox.com/sh/bwd5jdzth5mp9mj/AAAwsZRncn9lJFuqv5ZXAYMpa?dl=0 would work? Not sure where this photo should be put. On the homepage you meant?

- Regarding the University involvement: I am fine with the changes. However, I would want to rely on @edlich for this. The University's stakeholders really should be fine with that, too!

- Email: Yes, I would like having a forward-to-all address on clojured.de, I also don't mind if @edlich wants to keep getting them himself though. ;)

**Comment by martinklepsch** [comment]
I'll be traveling most of today, just that you know.

Making the contact us link to the contact page is a good workaround until
we have a proper email address. 👍

**Comment by nblumoe** [comment]
Alright, I changed the link. Merging...

**Comment by edlich** [comment]
Dear all,

sagt mal warum schreiben wir Englisch?

Ich kann in df.eu nur eine EMail Adresse hinterlegen. Soll ich diese github
Reply Adresse hinterlegen?
Aber natürlich würde ich alle EMail dort an Euch forwarden. Bis auf die
Vortragseinreichungen ist bisher auch
nichts anderes eingegangen.

Für die Frage mit dem Organisator finden wir doch eine einfache Lösung.
Irgendetwas mit dass die Hochschule the official operator (o.ä.) ist und
die Community in der fachlichen Organisation involviert ist.
Das muss doch leicht besser zu formulieren sein.

Viele Grüße
Stefan

On Wed, Sep 9, 2015 at 9:34 AM, Nils Blum-Oeste <notifications@github.com>
wrote:

> I really like the changes, would merge but we still have the missing
> "contact us" link. Could be changed to http://www.clojured.de/contact/ to
> make it "mergable".
>
> Regarding the additional proposals:
>
>    -
>
>    I am fine with Clojure(Script)
>    -
>
>    Regarding a nicer photo, maybe something from
>    https://www.dropbox.com/sh/bwd5jdzth5mp9mj/AAAwsZRncn9lJFuqv5ZXAYMpa?dl=0
>    would work? Not sure where this photo should be put. On the homepage you
>    meant?
>    -
>
>    Regarding the University involvement: I am fine with the changes.
>    However, I would want to rely on @edlich <https://github.com/edlich>
>    for this. The University's stakeholders really should be fine with that,
>    too!
>    -
>
>    Email: Yes, I would like having a forward-to-all address on clojured.de,
>    I also don't mind if @edlich <https://github.com/edlich> wants to keep
>    getting them himself though. ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojureD-conference/clojureD-conference.github.io/pull/12#issuecomment-138812728>
> .
>



-- 
Viele Grüße  Best Regards
Prof. Dr. *Stefan Edlich*

Beuth Hochschule für Technik, FB VI
Email: edlich@gmail.com  (GChat / Hangout)
Skype: sedlich
Tel.: (+49)(0)1577-189.42.16
http://edlich.de

**Pull request merged**
